title: 'Sentosa Development Corporation'
title-abbreviated: SDC
description: 'Developing a Fun, Smart, and Sustainable Sentosa'
url: 'https://www.sentosa.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
collections:
    who-we-are:
        output: true
    what-we-do:
        output: true
    partner-us:
        output: true
    careers:
        output: true
resources_name: resources
extra_javascript: myscript.js
favicon: /images/favicon.ico
google_analytics: null
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
